using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SkeletonBattleState : EnemyState
{
    private Transform player;
    private int moveDirection;
    private Skeleton skeleton;

    public SkeletonBattleState(Enemy enemyBase, EnemyStateMachine stateMachine, string animBoolName, Skeleton skeletonRef)
        : base(enemyBase, stateMachine, animBoolName)
    {
        skeleton = skeletonRef;
    }

    public override void Enter()
    {
        base.Enter();

        DelayTime = skeleton.aggressiveTime;
        player = PlayerManager.instance.player.transform;

        FacePlayer();

        if (player.GetComponent<PlayerStats>().isDead)
        {
            stateMachine.ChangeState(skeleton.MoveState);
        }
    }

    public override void Update()
    {
        if (skeleton.stats.currentHP <= 0)
        {
            anim.SetBool("Idle", false);
            anim.SetBool("Move", false);
            stateMachine.ChangeState(skeleton.DeathState);
            return;
        }

        if (skeleton.isJumping)
        {
            skeleton.SetVelocity(skeleton.battleMoveSpeed * skeleton.facingDirection, rb.velocity.y);
            ChangeToMoveAnimation();
            return;
        }

        base.Update();
        // Generated by ChatGPT, with some modifications for clarity and functionality.
        float distanceToPlayer = Vector2.Distance(player.position, skeleton.transform.position);

        if (distanceToPlayer <= skeleton.attackDistance && CanAttack())
        {
            anim.SetBool("Idle", false);
            anim.SetBool("Move", false);
            stateMachine.ChangeState(skeleton.AttackState);
            return;
        }

        FacePlayer();

        var detection = skeleton.IsPlayerDetected();

        if (detection.collider != null)
        {
            DelayTime = skeleton.aggressiveTime;

            if (detection.distance <= skeleton.attackDistance && CanAttack())
            {
                anim.SetBool("Idle", false);
                anim.SetBool("Move", false);
                stateMachine.ChangeState(skeleton.AttackState);
                return;
            }
        }
        else
        {
            float distance = Vector2.Distance(player.position, skeleton.transform.position);
            if (!skeleton.isJumping && (DelayTime < 0 || distance > skeleton.playerScanDistance))
            {
                stateMachine.ChangeState(skeleton.IdleState);
                return;
            }
        }

        if (skeleton.IsPlayerDetected().collider != null &&
            Vector2.Distance(player.position, skeleton.transform.position) <= skeleton.attackDistance)
        {
            skeleton.SetVelocity(0, rb.velocity.y);
            ChangeToIdleAnimation();
            return;
        }

        moveDirection = skeleton.GetMoveDirectionToTarget(player);

        if (!skeleton.IsGroundDetected())
        {
            skeleton.Jump(skeleton.battleMoveSpeed * moveDirection, skeleton.jumpForce);
            ChangeToMoveAnimation();
            return;
        }
        // Generated by ChatGPT, with some modifications for clarity and functionality.
        float distanceToPlayerX = Mathf.Abs(player.position.x - skeleton.transform.position.x);

        if (!skeleton.isJumping && skeleton.IsGroundDetected())
        {
            if (distanceToPlayerX > skeleton.attackDistance)
            {
                skeleton.SetVelocity(skeleton.battleMoveSpeed * moveDirection, rb.velocity.y);
                ChangeToMoveAnimation();
            }
            else
            {
                skeleton.SetVelocity(0, rb.velocity.y); 
                ChangeToIdleAnimation();
            }
        }
    }



    private bool CanAttack()
    {
        return Time.time - skeleton.lastTimeAttacked >= skeleton.attackCooldown && !skeleton.isKnockbacked && Mathf.Abs(rb.velocity.y) <= 0.1f;
    }

    private void ChangeToIdleAnimation()
    {
        if (!anim.GetBool("Idle"))
        {
            anim.SetBool("Move", false);
            anim.SetBool("Idle", true);
        }
    }

    private void ChangeToMoveAnimation()
    {
        if (!anim.GetBool("Move"))
        {
            anim.SetBool("Idle", false);
            anim.SetBool("Move", true);
        }
    }

    private void FacePlayer()
    {
        float deltaX = player.position.x - skeleton.transform.position.x;
        if ((deltaX < 0 && skeleton.facingDirection != -1) || (deltaX > 0 && skeleton.facingDirection != 1))
        {
            skeleton.Flip();
        }
    }
}
